# config/aws.yml
defaults: &defaults
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  region: <%=ENV["AWS_REGION"]%>
  bucket: <%=ENV["AWS_BUCKET_NAME"]%>
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
