default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: mtd
  password: password

development:
  <<: *default
  database: mtd_development

test:
  <<: *default
  database: mtd_test
